### PR TITLE
Add National Records of Scotland to archives list. Closes #107.

### LINKED ISSUE #107: Add National Records of Scotland in archives list
https://blog.nrscotland.gov.uk/2017/11/20/surfing-the-webarchive/

TG: http://webarchive.nrscotland.gov.uk/timegate/
TM: http://webarchive.nrscotland.gov.uk/timemap/

### PR DESCRIPTION
**Pull request by machawk1**

### CODE REVIEW

**Comment by ibnesayeed** [comment]
While we can merge this, it will not be effective immediately because the static file is not being served from the master branch. I was holding on to this for some other changes I am planning to make so that we do not serve GH Pages using a separate branch and maintain it in the master instead.

If you immediately need it, you might want to use a local file or send a PR against the `gh-pages` branch instead.

**Comment by machawk1** [comment]
@ibnesayeed I don't immediately need this change applied to the master branch.

> I was holding on to this...

It would have been useful to put this information in the ticket. ;)

Could you provide more information on what tickets need to be completed before this PR is to be applied?

**Comment by ibnesayeed** [comment]
> It would have been useful to put this information in the ticket. ;)

I mentioned that somewhere when this ticket was created, but I guess it was a verbal conversation with someone.

> Could you provide more information on what tickets need to be completed before this PR is to be applied?

I had a few assorted improvements to be made in the overall workflow, but nothing is really stopping it from being merged. There is no harm in merging it, but no immediate benefit either until things are reorganized. If you plan to merge it now, please go ahead, but leave the #107 ticket open so that we can track that it did not make it to the served static file yet.

**Comment by machawk1** [comment]
See #112 please, @ibnesayeed.

**Pull request merged**
